'use client'
import { useState } from 'react'

const styles = `
  :root {
    --ink: #0f0e0d;
    --paper: #faf7f2;
    --cream: #f2ede4;
    --amber: #c8862a;
    --amber-light: #e8a84a;
    --rust: #8b3a1e;
    --sage: #4a6741;
    --muted: #7a756e;
    --border: #d8d0c4;
  }
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: 'DM Sans', sans-serif; background: var(--paper); color: var(--ink); min-height: 100vh; }
`

type Step = 'idle' | 'generating' | 'done' | 'error'

export default function Home() {
  const [subject, setSubject] = useState('')
  const [objectives, setObjectives] = useState('')
  const [background, setBackground] = useState('')
  const [priorKnowledge, setPriorKnowledge] = useState('some basics')
  const [depth, setDepth] = useState('standard')
  const [step, setStep] = useState<Step>('idle')
  const [progressStep, setProgressStep] = useState(0)
  const [content, setContent] = useState('')
  const [title, setTitle] = useState('')
  const [error, setError] = useState('')

  async function generate() {
    if (!subject.trim()) { setError('Please enter a subject.'); return }
    if (!objectives.trim()) { setError('Please enter learning objectives.'); return }
    setError('')
    setStep('generating')
    setProgressStep(1)

    setTimeout(() => setProgressStep(2), 1200)
    setTimeout(() => setProgressStep(3), 2400)

    try {
      const res = await fetch('/api/generate-textbook', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ subject, objectives, background, priorKnowledge, depth })
      })

      const data = await res.json()
      if (!res.ok) throw new Error(data.error || 'Failed')

      setProgressStep(4)
      await new Promise(r => setTimeout(r, 600))
      setProgressStep(5)

      const titleMatch = data.content.match(/TEXTBOOK:\s*(.+)/)
      setTitle(titleMatch ? titleMatch[1].trim() : `${subject} — Personalized Textbook`)
      setContent(data.content)
      setStep('done')
    } catch (e: any) {
      setError(e.message)
      setStep('error')
    }
  }

  async function downloadPDF() {
    const jspdf = await import('jspdf')
    const { jsPDF } = jspdf
    const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })

    const pageW = doc.internal.pageSize.getWidth()
    const pageH = doc.internal.pageSize.getHeight()
    const margin = 20
    const contentW = pageW - margin * 2
    let y = margin

    function checkPage(needed = 10) {
      if (y + needed > pageH - margin) { doc.addPage(); y = margin }
    }

    // Cover
    doc.setFillColor(15, 14, 13)
    doc.rect(0, 0, pageW, pageH, 'F')
    doc.setFillColor(200, 134, 42)
    doc.rect(0, pageH - 8, pageW, 8, 'F')
    doc.setTextColor(255, 255, 255)
    doc.setFontSize(26)
    doc.setFont('helvetica', 'bold')
    const titleLines = doc.splitTextToSize(title, contentW - 10)
    let ty = 80
    titleLines.forEach((line: string) => { doc.text(line, margin, ty); ty += 11 })
    const subtitleMatch = content.match(/SUBTITLE:\s*(.+)/)
    if (subtitleMatch) {
      doc.setFontSize(11); doc.setFont('helvetica', 'normal'); doc.setTextColor(200, 180, 140)
      doc.splitTextToSize(subtitleMatch[1].trim(), contentW).forEach((l: string) => { doc.text(l, margin, ty); ty += 6 })
    }
    doc.setTextColor(100, 100, 100); doc.setFontSize(9)
    doc.text('Generated by LearnCraft · Powered by Claude AI', margin, pageH - 15)

    // Content
    doc.addPage(); y = margin
    doc.setTextColor(15, 14, 13)

    content.split('\n').forEach(line => {
      const t = line.trim()
      if (!t) { y += 3; checkPage(3); return }
      if (t.startsWith('CHAPTER ') && t.includes(':')) {
        checkPage(20)
        doc.setFillColor(245, 240, 232)
        doc.rect(margin - 4, y - 6, contentW + 8, 14, 'F')
        doc.setFontSize(13); doc.setFont('helvetica', 'bold'); doc.setTextColor(15, 14, 13)
        doc.text(t, margin, y); y += 12
      } else if (['PREFACE','TABLE OF CONTENTS','GLOSSARY','WHAT TO EXPLORE NEXT'].includes(t)) {
        checkPage(15)
        doc.setFontSize(13); doc.setFont('helvetica', 'bold'); doc.setTextColor(139, 58, 30)
        doc.text(t, margin, y); y += 9
      } else if (t === '---') {
        checkPage(8)
        doc.setDrawColor(210, 200, 190); doc.line(margin, y, pageW - margin, y); y += 6
      } else if (['Overview','Key Terms','Chapter Summary','Review Questions'].includes(t)) {
        checkPage(10)
        doc.setFontSize(10); doc.setFont('helvetica', 'bold'); doc.setTextColor(74, 103, 65)
        doc.text(t, margin, y); y += 7
      } else if (t.startsWith('TEXTBOOK:') || t.startsWith('SUBTITLE:') || t.startsWith('AUTHOR:')) {
        // skip
      } else {
        doc.setFontSize(9.5); doc.setFont('helvetica', 'normal'); doc.setTextColor(40, 38, 36)
        const wrapped = doc.splitTextToSize(t, contentW)
        wrapped.forEach((wl: string) => { checkPage(6); doc.text(wl, margin, y); y += 5.5 })
        y += 1
      }
    })

    // Page numbers
    const total = (doc.internal as any).getNumberOfPages()
    for (let i = 2; i <= total; i++) {
      doc.setPage(i); doc.setFontSize(8); doc.setFont('helvetica', 'normal'); doc.setTextColor(160, 150, 140)
      doc.text(String(i - 1), pageW / 2, pageH - 10, { align: 'center' })
      doc.text('LearnCraft · AI Textbook', margin, pageH - 10)
    }

    doc.save(title.replace(/[^a-z0-9]/gi, '_').toLowerCase().slice(0, 40) + '.pdf')
  }

  const steps = [
    'Analyzing your learning objectives...',
    'Designing curriculum & chapter structure...',
    'Writing personalized content & examples...',
    'Adding exercises, summaries & review questions...',
    'Finalizing your textbook...'
  ]

  return (
    <>
      <style>{styles}</style>
      <div style={{ minHeight: '100vh', background: 'var(--paper)' }}>

        {/* Header */}
        <header style={{ padding: '2rem 4rem', display: 'flex', alignItems: 'center', justifyContent: 'space-between', borderBottom: '1px solid var(--border)' }}>
          <div style={{ display: 'flex', alignItems: 'baseline', gap: '0.4rem' }}>
            <span style={{ fontFamily: 'Playfair Display, serif', fontSize: '1.6rem', fontWeight: 900, letterSpacing: '-0.02em' }}>LearnCraft</span>
            <div style={{ width: 8, height: 8, borderRadius: '50%', background: 'var(--amber)', marginBottom: 4 }} />
          </div>
          <span style={{ fontSize: '0.8rem', color: 'var(--muted)', letterSpacing: '0.12em', textTransform: 'uppercase', fontWeight: 500 }}>AI Textbook Generator</span>
        </header>

        {/* Hero */}
        <section style={{ padding: '5rem 4rem 3rem', maxWidth: 900, margin: '0 auto' }}>
          <div style={{ display: 'inline-flex', alignItems: 'center', gap: '0.5rem', background: 'var(--cream)', border: '1px solid var(--border)', padding: '0.35rem 0.9rem', borderRadius: 100, fontSize: '0.78rem', color: 'var(--amber)', fontWeight: 600, letterSpacing: '0.08em', textTransform: 'uppercase', marginBottom: '1.5rem' }}>
            <div style={{ width: 6, height: 6, borderRadius: '50%', background: 'var(--amber)' }} />
            Powered by Claude AI
          </div>
          <h1 style={{ fontFamily: 'Playfair Display, serif', fontSize: 'clamp(2.6rem, 5vw, 4rem)', fontWeight: 900, lineHeight: 1.08, letterSpacing: '-0.03em', marginBottom: '1.25rem' }}>
            Your subject.<br /><span style={{ color: 'var(--amber)', fontStyle: 'italic' }}>Your textbook.</span><br />In seconds.
          </h1>
          <p style={{ fontSize: '1.1rem', color: 'var(--muted)', lineHeight: 1.7, maxWidth: 560, fontWeight: 300 }}>
            Enter your learning objectives, your background, and how deep you want to go. Claude writes a full personalized textbook — yours to download as a PDF.
          </p>
        </section>

        {/* Form */}
        <section style={{ maxWidth: 900, margin: '0 auto 6rem', padding: '0 4rem' }}>
          <div style={{ background: 'white', border: '1px solid var(--border)', borderRadius: 16, padding: '3rem', boxShadow: '0 4px 32px rgba(0,0,0,0.06)' }}>

            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1.5rem', marginBottom: '1.5rem' }}>
              <div style={{ gridColumn: '1 / -1' }}>
                <label style={{ display: 'block', fontSize: '0.8rem', fontWeight: 600, letterSpacing: '0.08em', textTransform: 'uppercase', marginBottom: '0.5rem' }}>
                  Subject / Topic <span style={{ color: 'var(--amber)' }}>*</span>
                </label>
                <input
                  value={subject} onChange={e => setSubject(e.target.value)}
                  placeholder="e.g. Introduction to Machine Learning, Python for Finance..."
                  style={{ width: '100%', padding: '0.85rem 1rem', border: '1.5px solid var(--border)', borderRadius: 8, fontSize: '0.95rem', fontFamily: 'DM Sans, sans-serif', outline: 'none', background: 'var(--paper)' }}
                />
              </div>

              <div style={{ gridColumn: '1 / -1' }}>
                <label style={{ display: 'block', fontSize: '0.8rem', fontWeight: 600, letterSpacing: '0.08em', textTransform: 'uppercase', marginBottom: '0.5rem' }}>
                  Learning Objectives <span style={{ color: 'var(--amber)' }}>*</span>
                </label>
                <textarea
                  value={objectives} onChange={e => setObjectives(e.target.value)}
                  rows={5}
                  placeholder={"List what you want to understand after reading this textbook.\n\ne.g.\n• Understand what neural networks are\n• Build a basic model in Python\n• Know when to use ML vs traditional programming"}
                  style={{ width: '100%', padding: '0.85rem 1rem', border: '1.5px solid var(--border)', borderRadius: 8, fontSize: '0.95rem', fontFamily: 'DM Sans, sans-serif', outline: 'none', background: 'var(--paper)', resize: 'vertical', lineHeight: 1.6 }}
                />
                <div style={{ fontSize: '0.78rem', color: 'var(--muted)', marginTop: '0.25rem' }}>The more specific your objectives, the better the textbook</div>
              </div>

              <div>
                <label style={{ display: 'block', fontSize: '0.8rem', fontWeight: 600, letterSpacing: '0.08em', textTransform: 'uppercase', marginBottom: '0.5rem' }}>Your Background</label>
                <input
                  value={background} onChange={e => setBackground(e.target.value)}
                  placeholder="e.g. Finance professional, biology student..."
                  style={{ width: '100%', padding: '0.85rem 1rem', border: '1.5px solid var(--border)', borderRadius: 8, fontSize: '0.95rem', fontFamily: 'DM Sans, sans-serif', outline: 'none', background: 'var(--paper)' }}
                />
              </div>

              <div>
                <label style={{ display: 'block', fontSize: '0.8rem', fontWeight: 600, letterSpacing: '0.08em', textTransform: 'uppercase', marginBottom: '0.5rem' }}>Prior Knowledge</label>
                <select
                  value={priorKnowledge} onChange={e => setPriorKnowledge(e.target.value)}
                  style={{ width: '100%', padding: '0.85rem 1rem', border: '1.5px solid var(--border)', borderRadius: 8, fontSize: '0.95rem', fontFamily: 'DM Sans, sans-serif', outline: 'none', background: 'var(--paper)', appearance: 'none', cursor: 'pointer' }}
                >
                  <option value="complete beginner">Complete beginner</option>
                  <option value="some basics">Some basics</option>
                  <option value="intermediate">Intermediate</option>
                  <option value="advanced">Advanced</option>
                </select>
              </div>
            </div>

            {/* Depth */}
            <div style={{ height: 1, background: 'var(--border)', margin: '1.5rem 0' }} />
            <div style={{ fontSize: '0.78rem', fontWeight: 700, letterSpacing: '0.12em', textTransform: 'uppercase', color: 'var(--muted)', marginBottom: '1rem' }}>Depth & Detail Level</div>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '0.75rem' }}>
              {[
                { val: 'concise', label: 'Concise', sub: 'Key ideas only' },
                { val: 'standard', label: 'Standard', sub: 'Balanced depth' },
                { val: 'detailed', label: 'Detailed', sub: 'In-depth + exercises' },
                { val: 'comprehensive', label: 'Comprehensive', sub: 'Full reference' },
              ].map(d => (
                <div
                  key={d.val}
                  onClick={() => setDepth(d.val)}
                  style={{
                    padding: '1rem', border: `1.5px solid ${depth === d.val ? 'var(--amber)' : 'var(--border)'}`,
                    borderRadius: 10, cursor: 'pointer', background: depth === d.val ? '#fff8ee' : 'var(--paper)',
                    transition: 'all 0.2s'
                  }}
                >
                  <div style={{ fontSize: '0.9rem', fontWeight: 600, color: depth === d.val ? 'var(--amber)' : 'var(--ink)', marginBottom: '0.2rem' }}>{d.label}</div>
                  <div style={{ fontSize: '0.72rem', color: 'var(--muted)' }}>{d.sub}</div>
                </div>
              ))}
            </div>

            {/* Error */}
            {error && (
              <div style={{ marginTop: '1.5rem', padding: '1rem 1.25rem', background: '#fff0f0', border: '1.5px solid #ffb3b3', borderRadius: 10, fontSize: '0.9rem', color: 'var(--rust)' }}>
                ⚠ {error}
              </div>
            )}

            {/* Generate button */}
            <button
              onClick={generate}
              disabled={step === 'generating'}
              style={{
                width: '100%', padding: '1.1rem', background: step === 'generating' ? '#666' : 'var(--ink)',
                color: 'white', fontFamily: 'DM Sans, sans-serif', fontSize: '1rem', fontWeight: 600,
                border: 'none', borderRadius: 10, cursor: step === 'generating' ? 'not-allowed' : 'pointer',
                marginTop: '2rem', letterSpacing: '0.01em', transition: 'background 0.2s'
              }}
            >
              {step === 'generating' ? 'Generating your textbook...' : '✦ Generate My Textbook'}
            </button>

            {/* Progress */}
            {step === 'generating' && (
              <div style={{ marginTop: '2rem' }}>
                <div style={{ background: 'var(--cream)', borderRadius: 100, height: 6, overflow: 'hidden', marginBottom: '1.25rem' }}>
                  <div style={{ height: '100%', background: 'linear-gradient(90deg, var(--amber), var(--amber-light, #e8a84a))', borderRadius: 100, width: `${(progressStep / 5) * 100}%`, transition: 'width 0.5s ease' }} />
                </div>
                {steps.map((s, i) => (
                  <div key={i} style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', fontSize: '0.88rem', color: progressStep === i + 1 ? 'var(--ink)' : progressStep > i + 1 ? 'var(--sage)' : 'var(--muted)', opacity: progressStep >= i + 1 ? 1 : 0.4, marginBottom: '0.5rem', transition: 'all 0.3s' }}>
                    <div style={{ width: 20, height: 20, borderRadius: '50%', border: '2px solid currentColor', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '0.65rem', fontWeight: 700, flexShrink: 0, background: progressStep > i + 1 ? 'var(--sage)' : progressStep === i + 1 ? 'var(--amber)' : 'transparent', borderColor: progressStep > i + 1 ? 'var(--sage)' : progressStep === i + 1 ? 'var(--amber)' : 'currentColor', color: progressStep >= i + 1 ? 'white' : 'currentColor' }}>
                      {progressStep > i + 1 ? '✓' : progressStep === i + 1 ? '◌' : i + 1}
                    </div>
                    {s}
                  </div>
                ))}
              </div>
            )}

            {/* Result */}
            {step === 'done' && (
              <div style={{ marginTop: '2rem', padding: '2rem', background: '#f0faf0', border: '1.5px solid #a8d5a8', borderRadius: 12 }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', marginBottom: '1rem' }}>
                  <div style={{ width: 40, height: 40, background: 'var(--sage)', borderRadius: 10, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '1.2rem' }}>📖</div>
                  <div>
                    <div style={{ fontFamily: 'Playfair Display, serif', fontSize: '1.1rem', fontWeight: 700 }}>{title}</div>
                    <div style={{ fontSize: '0.82rem', color: 'var(--muted)', marginTop: 2 }}>{depth.charAt(0).toUpperCase() + depth.slice(1)} depth · Personalized for {background || 'you'}</div>
                  </div>
                </div>
                <button
                  onClick={downloadPDF}
                  style={{ display: 'inline-flex', alignItems: 'center', gap: '0.5rem', padding: '0.85rem 1.8rem', background: 'var(--sage)', color: 'white', fontFamily: 'DM Sans, sans-serif', fontSize: '0.95rem', fontWeight: 600, border: 'none', borderRadius: 8, cursor: 'pointer' }}
                >
                  ⬇ Download PDF Textbook
                </button>
                <div style={{ marginTop: '1.5rem', background: 'white', border: '1px solid var(--border)', borderRadius: 8, overflow: 'hidden' }}>
                  <div style={{ background: 'var(--cream)', padding: '0.6rem 1rem', fontSize: '0.78rem', color: 'var(--muted)', borderBottom: '1px solid var(--border)', fontWeight: 500 }}>
                    📄 Content Preview
                  </div>
                  <pre style={{ padding: '1.25rem', fontSize: '0.82rem', lineHeight: 1.7, color: 'var(--ink)', whiteSpace: 'pre-wrap', wordBreak: 'break-word', maxHeight: 360, overflowY: 'auto', fontFamily: 'monospace' }}>
                    {content.substring(0, 1800) + '\n\n[... continues in PDF ...]'}
                  </pre>
                </div>
              </div>
            )}

          </div>
        </section>

        {/* Footer */}
        <footer style={{ borderTop: '1px solid var(--border)', padding: '2rem 4rem', textAlign: 'center', fontSize: '0.82rem', color: 'var(--muted)' }}>
          LearnCraft · Built with Claude AI · Free to use
        </footer>

      </div>
    </>
  )
}
